### ISSUE TITLE
Can you give the physical meaning of the parameters?

### ISSUE THREAD

**Issue by lguduy** [mjambon/purple-fringe#3]
Hi. Thanks for your great work!
But I'm confused about these parameters, e.g. min_brightness, min_red_to_blue_ratio and max_red_to_blue_ratio. Can you give the physical meaning of these parameters. Thanks!

**Comment by mjambon** [comment]
Hi!

It's been a while since I made this and I don't remember exactly where those parameters come from. They're derived from trial and error. The general idea of the heuristic is to create a faint blur from the blue/purple component of the image, and then to subtract it from the original image; that's the main intuition that's related to actual optics. Everything else is tricks to avoid catastrophic results. A catastrophic result would be:
* introduction of new colors - that's why we tend to replace the original color with something greyer, because grey is an acceptable color for almost anything but not e.g. green or red.
* removal of colors that were legitimate - this is particularly hard to avoid when dealing with photos of blue or purple objects. I think this is what min_red_to_blue_ratio and max_red_to_blue_ratio are about. The source code is the best reference we have.

**Comment by lguduy** [comment]
Thanks for your reply. I will read source code carefully and try it.
